### ISSUE TITLE
Error 422: Unprocessable Entity

### ISSUE THREAD

**Issue by vekexasia** [iainbullock/tesla-http-proxy-docker#29]
Do you know what might be the case for this errorwhen "Registering Tesla account"?

**Comment by iainbullock** [comment]
No. Please provide debug logs

**Comment by vekexasia** [comment]
At the end it was a problem with re-setup. so i did recreate a new "app" within the tesla  developer website with a new domain etc...

**Comment by ybizeul** [comment]
FWIW I had the same issue because I had to change Tesla account, and was using the same domain in the new app I registered with my new account. After setting a different domain name it worked.
I didn't find a way to delete an application.

Just adding this here as this issue was pretty much all I found about 422

**Comment by iainbullock** [comment]
Thanks everyone for your comments
